import Head from "next/head";
import { tw } from "utils/tailwindMerge";

export default function Home() {
  return (
    <>
      <Head>
        <title>codeisneverodd</title>
        <meta
          name="description"
          content="Generated by codeisneverodd's starter kit"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Codeisneverodd</h1>
      </main>
    </>
  );
}
